#!/usr/bin/env ruby

require 'cpu'

if t_j_max = ENV['t_j_max']
  CPU.t_j_max = t_j_max.to_i
end

case ARGV.shift
when 'config'
  puts <<EOT
graph_title CPU Core temperatures
graph_args --base 1000 -l 0
graph_vtitle Celsius
graph_category sensors
EOT
  for c in CPU.cores
    puts "core#{c.core_id}.label Core #{c.core_id}"
  end
else
  for c in CPU.cores
    puts "core#{c.core_id}.value #{c.temperature}"
  end
end
