#!/usr/bin/env ruby

require 'msr'

if t_j_max = ENV['t_j_max']
  MSR::CPU.t_j_max = t_j_max.to_i
end

case ARGV.shift
when 'config'
  puts <<EOT
graph_title CPU Core temperatures
graph_args --base 1000 -l 0
graph_vtitle Celsius
graph_category sensors
EOT
  for c in MSR
    puts "cpu#{c.cpuid}.label Core #{c.cpuid}"
  end
else
  for c in MSR
    puts "cpu#{c.cpuid}.value #{c.temperature}"
  end
end
